
include:
  - ../common/compose.yml


services:
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    command:
      - "--name=${WHOAMI_NAME}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.local`)"
    deploy:
      replicas: 2
    networks:
      - frontend
