
include:
  - ../common/compose.yml

services:
  other-stuff:
    image: nginx:1.25
    labels:
      - "traefik.http.routers.other-stuff.rule=Host(`other-stuff.docker.localhost`)"
    volumes:
      - ./data:/usr/share/nginx/html:ro
    deploy:
      replicas: 1
    networks:
      - frontend
