
networks:
  frontend:
    name: global-frontend

services:
  traefik-proxy:
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # traefik configuration through an config file in etc/traefik.yml
      - ./etc/traefik.yml:/etc/traefik/traefik.yml

      # files.d is used for file based provider
      - ./files.d:/files.d
      # ssl certificates are persisten on disk
      - ssl-certs:/ssl-certs
    networks:
      - frontend

volumes:
  ssl-certs:

