
api:
  dashboard: true
  insecure: true

providers:
  docker:
    # use label traefik.enable=true to expose a docker container
    exposedByDefault: false

  file:
    # alternative config, file based
    directory: /files.d
    watch: true
